" Editor options
colorscheme Tomorrow-Night

set background=dark
set guioptions-=r
set guioptions-=L
set number
set ruler

" Temp files
set backupdir=~/.vim/tmp/backup//
set directory=~/.vim/tmp/swap//
set undodir=~/.vim/tmp/undo//

set softtabstop=4
set shiftwidth=4
set expandtab

" Tabs
autocmd FileType ruby setlocal shiftwidth=2 softtabstop=2
autocmd FileType eruby setlocal shiftwidth=2 softtabstop=2
autocmd FileType yaml setlocal shiftwidth=2 softtabstop=2
autocmd FileType json setlocal shiftwidth=2 softtabstop=2
autocmd FileType scss setlocal shiftwidth=2 softtabstop=2
autocmd FileType javascript setlocal shiftwidth=2 softtabstop=2
autocmd FileType html.handlebars setlocal shiftwidth=2 softtabstop=2

" Show whitespaces
set list

" Leader key
let mapleader=","

" Search
set hlsearch

" Pathogen
execute pathogen#infect()

" Options
set nocompatible      " We're running Vim, not Vi!
syntax on             " Enable syntax highlighting
filetype on           " Enable filetype detection
filetype indent on    " Enable filetype-specific indenting
filetype plugin on    " Enable filetype-specific plugins

" NERDTree
nmap <F8> :NERDTreeToggle<CR>

let g:NERDTreeShowHidden=1
let g:NERDTreeIgnore = ['\.DS_Store$', '\.git$']
let g:NERDTreeHijackNetrw=0

" Go
let g:go_disable_autoinstall = 1
let g:go_fmt_fail_silently = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

" Ruby
autocmd FileType ruby compiler ruby

" Custom syntax highlighting
autocmd BufRead,BufNewFile Gomfile setlocal ft=ruby
autocmd BufRead,BufNewFile Caskfile setlocal ft=ruby
autocmd BufRead,BufNewFile *.es6 set filetype=javascript
autocmd BufRead,BufReadPost *.md set filetype=markdown
autocmd BufRead,BufNewFile *.docker set filetype=dockerfile

" Remove trailing whitespaces on save
set wrap
set linebreak
set showbreak=>\ \ \
autocmd BufWritePre * :%s/\s\+$//e

" Tagbar
nmap <F9> :TagbarToggle<CR>

" Split panes
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Fuzzy finder
set rtp+=~/.fzf
nmap <C-P> :FZF<CR>

" Ripgrep
nmap <C-S-F> :Rg<space>
