# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Background color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.bg = '#2d2d2d'

# Bottom border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.bottom = '#333333'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.category.border.top = '#333333'

# Foreground color of completion widget category headers.
# Type: QtColor
c.colors.completion.category.fg = '#f9f9f9'

# Background color of the completion widget for even rows.
# Type: QssColor
c.colors.completion.even.bg = '#333333'

# Text color of the completion widget.
# Type: QtColor
c.colors.completion.fg = '#f9f9f9'

# Background color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.bg = '#dedede'

# Bottom border color of the selected completion item.
# Type: QssColor
c.colors.completion.item.selected.border.bottom = '#dedede'

# Top border color of the completion widget category headers.
# Type: QssColor
c.colors.completion.item.selected.border.top = '#dedede'

# Foreground color of the selected completion item.
# Type: QtColor
c.colors.completion.item.selected.fg = '#2d2d2d'

# Foreground color of the matched text in the completion.
# Type: QssColor
c.colors.completion.match.fg = '#d64937'

# Background color of the completion widget for odd rows.
# Type: QssColor
c.colors.completion.odd.bg = '#2d2d2d'

# Color of the scrollbar in completion view
# Type: QssColor
c.colors.completion.scrollbar.bg = '#2d2d2d'

# Color of the scrollbar handle in completion view.
# Type: QssColor
c.colors.completion.scrollbar.fg = '#333333'

# Background color for the download bar.
# Type: QssColor
c.colors.downloads.bar.bg = '#2d2d2d'

# Background color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.bg = '#d64937'

# Foreground color for downloads with errors.
# Type: QtColor
c.colors.downloads.error.fg = '#f9f9f9'

# Color gradient start for download backgrounds.
# Type: QtColor
c.colors.downloads.start.bg = '#067bc2'

# Color gradient start for download text.
# Type: QtColor
c.colors.downloads.start.fg = '#f9f9f9'

# Color gradient stop for download backgrounds.
# Type: QtColor
c.colors.downloads.stop.bg = '#138a36'

# Color gradient end for download text.
# Type: QtColor
c.colors.downloads.stop.fg = '#f9f9f9'

# Background color for hints. Note that you can use a `rgba(...)` value
# for transparency.
# Type: QssColor
c.colors.hints.bg = '#d64937'

# Font color for hints.
# Type: QssColor
c.colors.hints.fg = '#f9f9f9'

# Font color for the matched part of hints.
# Type: QssColor
c.colors.hints.match.fg = '#d64937'

# Background color of the keyhint widget.
# Type: QssColor
c.colors.keyhint.bg = '#2d2d2d'

# Text color for the keyhint widget.
# Type: QssColor
c.colors.keyhint.fg = '#f9f9f9'

# Highlight color for keys to complete the current keychain.
# Type: QssColor
c.colors.keyhint.suffix.fg = '#d64937'

# Background color of an error message.
# Type: QssColor
c.colors.messages.error.bg = '#d64937'

# Border color of an error message.
# Type: QssColor
c.colors.messages.error.border = '#d64937'

# Foreground color of an error message.
# Type: QssColor
c.colors.messages.error.fg = '#f9f9f9'

# Background color of an info message.
# Type: QssColor
c.colors.messages.info.bg = '#2d2d2d'

# Border color of an info message.
# Type: QssColor
c.colors.messages.info.border = '#333333'

# Foreground color an info message.
# Type: QssColor
c.colors.messages.info.fg = '#f9f9f9'

# Background color of a warning message.
# Type: QssColor
c.colors.messages.warning.bg = '#ec4e20'

# Border color of a warning message.
# Type: QssColor
c.colors.messages.warning.border = '#ec4e20'

# Foreground color a warning message.
# Type: QssColor
c.colors.messages.warning.fg = '#f9f9f9'

# Background color for prompts.
# Type: QssColor
c.colors.prompts.bg = '#333333'

# Border used around UI elements in prompts.
# Type: String
c.colors.prompts.border = '1px solid #dedede'

# Foreground color for prompts.
# Type: QssColor
c.colors.prompts.fg = '#f9f9f9'

# Background color for the selected item in filename prompts.
# Type: QssColor
c.colors.prompts.selected.bg = '#2d2d2d'

# Background color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.bg = '#7f0799'

# Foreground color of the statusbar in caret mode.
# Type: QssColor
c.colors.statusbar.caret.fg = '#f9f9f9'

# Background color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.bg = '#998fc7'

# Foreground color of the statusbar in caret mode with a selection.
# Type: QssColor
c.colors.statusbar.caret.selection.fg = '#f9f9f9'

# Background color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.bg = '#2d2d2d'

# Foreground color of the statusbar in command mode.
# Type: QssColor
c.colors.statusbar.command.fg = '#f9f9f9'

# Background color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.bg = '#333333'

# Foreground color of the statusbar in private browsing + command mode.
# Type: QssColor
c.colors.statusbar.command.private.fg = '#f9f9f9'

# Background color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.bg = '#138a36'

# Foreground color of the statusbar in insert mode.
# Type: QssColor
c.colors.statusbar.insert.fg = '#f9f9f9'

# Background color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.bg = '#2d2d2d'

# Foreground color of the statusbar.
# Type: QssColor
c.colors.statusbar.normal.fg = '#f9f9f9'

# Foreground color of the statusbar in passthrough mode.
# Type: QssColor
c.colors.statusbar.passthrough.fg = '#f9f9f9'

# Background color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.bg = '#333333'

# Foreground color of the statusbar in private browsing mode.
# Type: QssColor
c.colors.statusbar.private.fg = '#f9f9f9'

# Background color of the progress bar.
# Type: QssColor
c.colors.statusbar.progress.bg = '#f9f9f9'

# Foreground color of the URL in the statusbar on error.
# Type: QssColor
c.colors.statusbar.url.error.fg = '#ec4e20'

# Default foreground color of the URL in the statusbar.
# Type: QssColor
c.colors.statusbar.url.fg = '#f9f9f9'

# Foreground color of the URL in the statusbar for hovered links.
# Type: QssColor
c.colors.statusbar.url.hover.fg = '#f9f9f9'

# Foreground color of the URL in the statusbar on successful load
# (http).
# Type: QssColor
c.colors.statusbar.url.success.http.fg = '#f9f9f9'

# Foreground color of the URL in the statusbar on successful load
# (https).
# Type: QssColor
c.colors.statusbar.url.success.https.fg = '#f9f9f9'

# Foreground color of the URL in the statusbar when there's a warning.
# Type: QssColor
c.colors.statusbar.url.warn.fg = '#ffe74c'

# Background color of the tab bar.
# Type: QtColor
c.colors.tabs.bar.bg = '#dedede'

# Background color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.bg = '#333333'

# Foreground color of unselected even tabs.
# Type: QtColor
c.colors.tabs.even.fg = '#999999'

# Color for the tab indicator on errors.
# Type: QtColor
c.colors.tabs.indicator.error = '#d64937'

# Color gradient start for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.start = '#067bc2'

# Color gradient end for the tab indicator.
# Type: QtColor
c.colors.tabs.indicator.stop = '#138a36'

# Background color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.bg = '#333333'

# Foreground color of unselected odd tabs.
# Type: QtColor
c.colors.tabs.odd.fg = '#999999'

# Background color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.bg = '#2d2d2d'

# Foreground color of selected even tabs.
# Type: QtColor
c.colors.tabs.selected.even.fg = '#f9f9f9'

# Background color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.bg = '#2d2d2d'

# Foreground color of selected odd tabs.
# Type: QtColor
c.colors.tabs.selected.odd.fg = '#f9f9f9'

# Background color for webpages if unset (or empty to use the theme's
# color)
# Type: QtColor
c.colors.webpage.bg = '#f9f9f9'

# How to format timestamps (e.g. for the history completion).
# Type: TimestampTemplate
c.completion.timestamp_format = '%d/%m/%Y'

# Allow websites to request geolocations.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
c.content.geolocation = True

# Whether locally loaded documents are allowed to access remote urls.
# Type: Bool
c.content.local_content_can_access_remote_urls = True

# Validate SSL handshakes.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
c.content.ssl_strict = False

# Prompt the user for the download location. If set to false,
# `downloads.location.directory` will be used.
# Type: Bool
c.downloads.location.prompt = False

# Where to show the downloaded files.
# Type: VerticalPosition
# Valid values:
#   - top
#   - bottom
c.downloads.position = 'bottom'

# Number of milliseconds to wait before removing finished downloads. If
# set to -1, downloads are never removed.
# Type: Int
c.downloads.remove_finished = 5000

# The editor (and arguments) to use for the `open-editor` command. `{}`
# gets replaced by the filename of the file to be edited.
# Type: ShellCommand
c.editor.command = ['vim', '-f', '{}']

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 10pt monospace'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '10pt monospace'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '10pt monospace'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '10pt monospace'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 13pt monospace'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt monospace'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '10pt monospace'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '10pt monospace'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '10pt monospace'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = 'Open Sans'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10pt monospace'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt monospace'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = '10pt monospace'

# CSS border value for hints.
# Type: String
c.hints.border = '1px solid #f9f9f9'

# Show a filebrowser in upload/download prompts.
# Type: Bool
c.prompt.filebrowser = False

# Definitions of search engines which can be used via the address bar.
# Maps a searchengine name (such as `DEFAULT`, or `ddg`) to a URL with a
# `{}` placeholder. The placeholder will be replaced by the search term,
# use `{{` and `}}` for literal `{`/`}` signs. The searchengine named
# `DEFAULT` is used when `url.auto_search` is turned on and something
# else than a URL was entered to be opened. Other search engines can be
# used by prepending the search engine name to the search term, e.g.
# `:open google qutebrowser`.
# Type: Dict
c.url.searchengines = {'DEFAULT': 'https://google.com/search?q={}'}

# The page(s) to open at the start.
# Type: List of FuzzyUrl, or FuzzyUrl
c.url.start_pages = 'https://calendar.google.com/calendar/b/1/render?pli=1#main_7'

# The format to use for the window title. The following placeholders are
# defined:  * `{perc}`: The percentage as a string like `[10%]`. *
# `{perc_raw}`: The raw percentage, e.g. `10` * `{title}`: The title of
# the current web page * `{title_sep}`: The string ` - ` if a title is
# set, empty otherwise. * `{id}`: The internal window ID of this window.
# * `{scroll_pos}`: The page scroll position. * `{host}`: The host of
# the current web page. * `{backend}`: Either ''webkit'' or
# ''webengine'' * `{private}` : Indicates when private mode is enabled.
# * `{current_url}` : The url of the current web page.
# Type: FormatString
c.window.title_format = '{perc}{title} {private}'
