# Reference: https://github.com/i3/i3/blob/next/etc/config

# Start AeroSpace at login
start-at-login = true

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[mode.main.binding]
    # Shift focus in a given direction.
    alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
    alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
    alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
    alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

    # Move focused window in a given direction.
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # As an alternative to the resize keybindings above, resize mode enables
    # resizing via arrow keys or HJKL. The binding mode is defined above with
    # the name 'resize'.
    alt-r = 'mode resize'

    # Change tiling direction. This determines where new tiling windows will
    # be inserted.
    alt-semicolon = 'split horizontal'
    alt-v = 'split vertical'

    # Change the focused window to be tiling.
    alt-t = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    # Change the focused window to be fullscreen.
    alt-f = 'fullscreen'

    # Close focused window.
    alt-q = 'close --quit-if-last-window'

    # 'layout stacking' in i3
    alt-n = 'layout v_accordion'

    # 'layout tabbed' in i3
    alt-p = 'layout h_accordion'

    # 'floating toggle' in i3
    alt-shift-space = 'layout floating tiling'

    # Re-evaluate configuration file.
    alt-shift-r = 'reload-config'

    # Launch terminal.
    alt-enter = 'exec-and-forget open -n -a WezTerm'

    # Launch web browser
    alt-b = 'exec-and-forget open -n -a "Google Chrome"'

    # Launch AI chat
    alt-i = 'exec-and-forget open -a "Google Gemini"'

    # Launch color picker
    alt-c = 'exec-and-forget open -a "Digital Color Meter"'

    # Launch file explorer
    alt-e = 'exec-and-forget open -n -a WezTerm --args start -- yazi ~'

    # Launch settings
    alt-s = 'exec-and-forget open -n -a "System Settings"'

    # Lock computer
    alt-shift-x = 'exec-and-forget osascript -e "delay 0.2" -e "tell application \"System Events\" to keystroke \"q\" using {control down, command down}"'

    # Change focus to a workspace.
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'

    # Move the focused window's parent workspace to another monitor.
    alt-shift-d = 'move-workspace-to-monitor --wrap-around next'

    # Move focused window to a workspace.
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'
