[remap]
# Maps Copilot (Meta+Shift+F23) to a clean Super key
KEY_LEFTMETA-KEY_LEFTSHIFT-KEY_F23 = ["KEY_LEFTMETA"]

[settings]
# Necessary to suppress the original hardware signals
GRAB_DEVICE = "true"