#!/bin/sh

export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

export SUDO_ASKPASS=$HOME/.local/bin/askpass

export PATH="$HOME/.local/bin:$PATH"

monitors-information current_mode > /tmp/monitor_mode.dat

# Watch monitors and fallback if necessary
pkill dbus-monitor
watch-monitors &

# Auto-mount usb devices
udiskie &

# Lock on suspend
xss-lock -- dm-tool switch-to-greeter &

load-keyboard-layout

switch-dpi

# Load compositor
compton -b

# Restore wallpaper
nitrogen --restore
