# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Environment variables
export EDITOR=nvim
export VISUAL=nvim
export SHELL=$(which bash)
export TERM=xterm-256color
export LC_ALL=en_US.UTF-8
export PAGER=most

if [ -d "/opt/homebrew/bin" ]; then
    export PATH="/opt/homebrew/bin:$PATH"
fi

if [ -d "/home/linuxbrew" ]; then
    export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
    export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar"
    export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew"

    export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"

    if [ -n "$MANPATH" ]; then
        export MANPATH=":$MANPATH"
    fi
    case ":$INFOPATH:" in
        *:/home/linuxbrew/.linuxbrew/share/info:*) ;;
        *) export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:$INFOPATH" ;;
    esac

    export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3)"
fi

export PATH="$HOME/.local/bin:$PATH"

# Ruby
if command -v rbenv >/dev/null 2>&1; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

# Node.js
if command -v fnm >/dev/null 2>&1; then
    eval "$(fnm env --use-on-cd)"
fi

set -o vi

# Aliases
if command -v eza >/dev/null 2>&1; then
    alias ll='eza -lF --icons'
    alias la='eza -lA --icons'
fi

if command -v zoxide >/dev/null 2>&1; then
    alias z='zoxide'
fi

if command -v hub  >/dev/null 2>&1; then
    alias git='hub'
fi

if command -v lazygit  >/dev/null 2>&1; then
    alias lzg='lazygit'
fi

if command -v lazydocker  >/dev/null 2>&1; then
    alias lzd='lazydocker'
fi

# Prompt setup
eval "$(starship init bash)"

swork() {
  $HOME/.config/tmux/switch_workspace.sh "$1" true
}

iwork() {
  $HOME/.config/tmux/switch_workspace.sh "$PWD" false
}

# Load local customizations if they exist
[ -f "$HOME/.bashrc.local" ] && source "$HOME/.bashrc.local"

# Load AWS CLI configuration if it exists
[ -f "$HOME/.aws/cli.bash" ] && source "$HOME/.aws/cli.bash"
