name: "Update Pull Request"
on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    - uses: the-wright-jamie/update-pr-info-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: 'master'
        head-branch-regex: 'develop'
        title-template: "feat: Release ${{ steps.date.outputs.DATE }}"
        title-update-action: 'replace'
        body-template: |
          Merging into '%basebranch%'
          *** DO NOT SQUASH THIS PR ***
        body-update-action: 'suffix'
        body-uppercase-base-match: false
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ github.base_ref == 'master' && github.head_ref == 'develop' }}
      with:
        labels: Release

