name: Update release PR

on:
  pull_request:
    branches:
      -master 

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
    - uses: the-wright-jamie/update-pr-info-action@v1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        base-branch-regex: 'master'
        head-branch-regex: 'develop'
        title-template: "feat: Release ${{ steps.date.outputs.DATE }}"
        title-update-action: 'replace'
        body-template: |
          If you want to release a minor or major version, please suffix the PR title with `--major` or `--minor`
          Default behavior is patch version.
          Merging into '%basebranch%'
          **DO NOT SQUASH THIS PR**
        body-update-action: 'replace'
        body-uppercase-base-match: false
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ github.base_ref == 'master' && github.head_ref == 'develop' }}
      with:
        labels: Release

