name: "Update Pull Request"
on:
  push:
    branches:
      - develop

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event_name }} ${{ github.event}}"