name: "Find pull request number"
on:
  push:
    branches:
      - develop

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event_name }} "
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0
    - name: Get Pull Request Number
      id: pr
      run: echo "::set-output name=pull_request_number::$(gh pr view --json number -q .number || echo "")"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ${{ steps.pr.outputs.pull_request_number }}
