name: Run tests on Bazzite

on:
  push:
    branches:
      - "*"

jobs:
  run-test-bazzite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          load: true
          tags: dotfiles:bazzite
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run linting
        run: docker run --rm dotfiles:bazzite make lint

      - name: Run tests
        run: docker run --rm dotfiles:bazzite make test
