name: Run tests on Ubuntu

on:
  push:
    branches:
      - "*"

jobs:
  run-test-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          chmod +x os/ubuntu/dependencies.sh
          sudo ./os/ubuntu/dependencies.sh system

      - name: Install brew
        run: |
          ./os/ubuntu/dependencies.sh homebrew
          echo "PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH" >> "$GITHUB_ENV"
          echo "HOMEBREW_NO_ANALYTICS=1" >> "$GITHUB_ENV"

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./os/ubuntu/dependencies.sh packages

      - name: Run Linting
        run: |
          make lint

      - name: Run tests
        run: |
          make test
