name: Run tests on Ubuntu

on:
  push:
    branches:
      - "*"

jobs:
  run-test-ubuntu:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system packages
        run: |
          chmod +x os/ubuntu/dependencies.sh
          sudo ./os/ubuntu/dependencies.sh install_ubuntu_deps

      - name: Install brew
        run: |
          ./os/ubuntu/dependencies.sh install_homebrew

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_PREFIX: /home/linuxbrew/.linuxbrew
          HOMEBREW_CELLAR: /home/linuxbrew/.linuxbrew/Cellar
          HOMEBREW_REPOSITORY: /home/linuxbrew/.linuxbrew/Homebrew
          PATH: /home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH
        run: |
          ./os/ubuntu/dependencies.sh install_shared_deps

      - name: Run tests
        run: |
          chmod +x run-tests.exp
          ./run-tests.exp