name: Run tests on Ubuntu

on:
  push:
    branches:
      - "*"

jobs:
  run-test-ubuntu:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install brew
        run: |
          chmod +x os/linux/ubuntu.sh
          ./os/linux/ubuntu.sh
          echo "PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH" >> $GITHUB_ENV
          echo "HOMEBREW_NO_ANALYTICS=1" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x os/linux/dependencies.sh
          ./os/linux/dependencies.sh

      - name: Run tests
        run: |
          chmod +x run-tests.exp
          ./run-tests.exp
