name: Run tests on Ubuntu

on:
  push:
    branches:
      - "*"

jobs:
  run-test-ubuntu:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install brew
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential procps curl file git python3 sudo locales
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH" >> $GITHUB_ENV
          echo "HOMEBREW_NO_ANALYTICS=1" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          chmod +x os/linux/dependencies.sh
          ./os/linux/dependencies.sh

      - name: Run tests
        run: |
          chmod +x run-tests.exp
          ./run-tests.exp
