name: Run tests on macOS

on:
  push:
    branches:
      - "*"

jobs:
  run-test-darwin:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x os/macOS/dependencies.sh
          ./os/macOS/dependencies.sh

      - name: Run tests
        run: |
          chmod +x run-tests.exp
          ./run-tests.exp
