name: Run tests on Ubuntu

on:
  push:
    branches:
      - "*"

jobs:
  run-test-ubuntu:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install system packages
        run: |
          chmod +x os/ubuntu/dependencies.sh
          sudo ./os/ubuntu/dependencies.sh system

      - name: Install brew
        run: |
          ./os/ubuntu/dependencies.sh homebrew
          echo "PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH" >> $GITHUB_ENV
          echo "HOMEBREW_NO_ANALYTICS=1" >> $GITHUB_ENV

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./os/ubuntu/dependencies.sh packages

      - name: Run Linting
        run: |
          stylua --config-path nvim/stylua.toml --check nvim/

      - name: Run tests
        run: |
          chmod +x run-tests.exp
          ./run-tests.exp
