#!/bin/sh
set -e

if [ "$(uname -s)" = "Darwin" ]; then
  CONFIG_DIR="$HOME/Library/Application Support"
else
  CONFIG_DIR="$HOME/.config"
fi

install_tuis() (
  for tui in $1; do
    tui_config_dir="$2/$tui"

    mkdir -p "$tui_config_dir"
    rm -rf "${tui_config_dir:?}"/*
    cp -r "$PWD/tuis/$tui"/* "$tui_config_dir/"
  done
)

install_tuis "k9s lazygit lazydocker" "$CONFIG_DIR"

install_tuis "yazi opencode" "$HOME/.config"

# Install the Madness theme while preserving settings generated by tools
# such as RTK.
mkdir -p "$HOME/.claude"
mkdir -p "$HOME/.claude/themes"
claude_theme_tmp="$(mktemp)"
curl -fsSL "https://raw.githubusercontent.com/foliea/omarchy-madness-theme/master/claude.json" \
  -o "$claude_theme_tmp"
mv "$claude_theme_tmp" "$HOME/.claude/themes/madness.json"
claude_settings="$HOME/.claude/settings.json"
claude_settings_tmp="$(mktemp)"
if [ -f "$claude_settings" ]; then
  jq '.theme = "custom:madness"' "$claude_settings" >"$claude_settings_tmp"
else
  printf '{"theme":"custom:madness"}\n' >"$claude_settings_tmp"
fi
mv "$claude_settings_tmp" "$claude_settings"

if ! command -v omarchy-version >/dev/null 2>&1; then
  install_tuis "fastfetch" "$HOME/.config/fastfetch"

  mkdir -p "$HOME/.config/btop/themes"
  curl -fsSL "https://raw.githubusercontent.com/foliea/omarchy-madness-theme/master/btop.theme" \
    -o "$HOME/.config/btop/themes/current.theme"
fi
